### ISSUE TITLE
Fix checks for Pull Requests

### ISSUE THREAD

**Issue by theperu** [RIP-Comm/sossoldi#139]
For a while we had this issue that the checks fail for every new PR. From my understanding we are using the wrong Dart SDK version (3.1.0) while it should be >=3.1.5 and <4.0.0

**Comment by mikev-cw** [comment]
Yeah, problem is surely this. Workflow configuration file, however, is correctly running on SDK version 3.16.0 as you can see here:
https://github.com/RIP-Comm/sossoldi/blob/3b83bf40918589cc11075e37dc12df9808f951b6/.github/workflows/flutter-ci.yml#L20
So it's not clear to me where the problem is.. i will try to investigate further

**Comment by theperu** [comment]
Maybe we could try running `flutter upgrade --dart` just to make sure that we have the latest compatible version of Dart?

**Comment by mikev-cw** [comment]
I don't think this is related to our local environments. Now seems that clearing GH Actions cache (again) does the job... let me check again on that on next days. 

...but now there are a couple of problems on tests, which were hidden 'till now by this issue! 🤣

**Comment by theperu** [comment]
Understood 👍🏻😂
